### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by garygreen** [danilopolani/sequel-bun#1]
This seems like a really interesting project. Noticed there's been no updates for a few years, any reason you abandoned it? Did you find an alternative or ran into anything that caused you to stop developing? 😄

**Comment by danilopolani** [comment]
Hello @garygreen 
thank you for your interest first of all. A huge problem I found out with Electron and Vue is that it can't handle easily some "bigger" structure, for example I tested it with a table with ~54 columns and like 500 rows and it was soooo slow, too much. Using virtual scrolls didn't help, also because the scroll issue was both vertical and horizontal, so I would stick with another language rather than this. I would check PyGObject in the future and, in case, update/redirect this repo

**Comment by garygreen** [comment]
I did give it a spin yesterday and experienced the same thing as you, it does feel pretty sluggish. In particular clicking around / editing cells. Scrolling performance wasn't too bad. I'm guessing the bottleneck really all comes down to Vue and performance of how it renders?

Out of interest I created a little test which renders lots of columns / cells to see performance. It does feel a fair bit quicker than sequel-bun, scrolling is good and editing is much faster. Though if you added more rows e.g. 500 rows it'll start to take a good 10 seconds or so to render the full list. I have coded the example to rely on properties on actual objects rather than the master instance, so not sure if Vue renders more efficiently due to watching the data for changes and can re-render/diff the minimal amount of elements.

https://codesandbox.io/s/88wj27mj38

Vue 3.0 is on the horizon and it features big performance improvements, so maybe things can be re-tested then to see if there's any improvement.

If not, maybe a hybrid approach could work - anything that's really heavy on data can just be done in vanilla js, but coded in a modern-component like way. With this much data being rendered, it's going to really test any rendering framework and probably calls for a bespoke approach anyway.

**Comment by danilopolani** [comment]
I can't run the sandbox due to a Babel error :/ btw I guess you're right about the data render/watching issue. We will see with Vue 3, but I'm pretty sure the problem will persist, maybe we can try as you said to manage data with vanillajs and other stuff with Vue, but honestly I think javascript is not "designed" to handle big arrays of data. 

A solution with JS could be preallocating an array and then use a pseudo-infinite scroll, I mean: we load only the first 50 rows, then others 50 and so on, but it would generate more queries and it can be slow/not so well for many users. I would give a try to Pygobject or Qt for Python or C++ in the future, unfortunately at this time I'm very busy and I can't, but I'm going to update here when I found out a valid solution!
